name: Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            suffix: linux-amd64
          - runner: ubuntu-24.04-arm
            suffix: linux-arm64
          - runner: windows-2025
            suffix: windows-amd64.exe
          - runner: windows-11-arm
            suffix: windows-arm64.exe
          - runner: macos-15-intel
            suffix: macos-amd64
          - runner: macos-26
            suffix: macos-arm64
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Build
        run: CGO_ENABLED=1 go build -v -o ./bin/dbdiff-${{ matrix.platform.suffix }} ./cmd/dbdiff

  test:
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            suffix: linux-amd64
          - runner: ubuntu-24.04-arm
            suffix: linux-arm64
          - runner: windows-2025
            suffix: windows-amd64.exe
          - runner: windows-11-arm
            suffix: windows-arm64.exe
          - runner: macos-15-intel
            suffix: macos-amd64
          - runner: macos-26
            suffix: macos-arm64
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Run Tests
        run: go test -v ./...
